name = "nodecrypt"
main = "worker/index.ts"
compatibility_date = "2024-01-01"

[[durable_objects.bindings]]
name = "ROOM_DURABLE_OBJECT"
class_name = "RoomDurableObject"

[build]
command = "npm run build:worker"

[exports.RoomDurableObject]
type = "durable-object"
storage = "sqlite"
