name = "room-worker"
main = "src/index.js"
compatibility_date = "2026-07-07"
type = "javascript"
account_id = "YOUR_ACCOUNT_ID"

[durable_objects]
bindings = [
  { name = "ROOMS", class_name = "Room" }
]
