name = "nodema-ws"
main = "src/index.ts"
compatibility_date = "2026-07-01"

[build]
command = "npm install --legacy-peer-deps && npm run build"

[[routes]]
pattern = "mi.8818618.xyz/ws/*"
zone_id = "your_zone_id"

